kind : Service
apiVersion: v1
metadata :
  name : dumbpad-service
  namespace : nginx
spec :
  selector :
    app : dumbpad
  ports:
  - protocol: TCP
    port : 3000
    targetPort : 3000
  type : ClusterIP

