kind: PersistentVolume
apiVersion: v1
metadata:
  name: localpv
  namespace: nginx
  labels :
    app: local

spec:
  capacity:
    storage: 1.5Gi
  # volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
      path:  /mnt/data
