apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  namespace : apache1
spec:
  replicas : 2
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      name : apache
      labels:
        app: apache

    spec:
      containers:
      - name: apache
        image: httpd:latest
        ports :
        - containerPort: 80

        resources:
          requests :
            cpu: 100m
            memory: 128Mi
          limits:
            memory: 128Mi
            cpu: 500m
